deployment:
  tasks:
    - /bin/echo "🚀 Iniciando deploy CorretorPRO DEV"

    - export DEPLOYPATH=/home/mapfrecorretor/public_html/dev
    - export VERSAO=$(date +%Y%m%d%H%M%S)

    # Copia tudo para a pasta dev, exceto o .cpanel.yml e vendor
    - /bin/rsync -a --exclude='.git*' --exclude='vendor/' --exclude='.cpanel.yml' . $DEPLOYPATH

    # Gera o .env substituindo as variáveis do template
    - sed "s/{{CSS_VERSION}}/$VERSAO/" .env.template | sed "s/{{JS_VERSION}}/$VERSAO/" > $DEPLOYPATH/.env

    # Log para depuração
    - echo "Versão gerada: $VERSAO" > $DEPLOYPATH/deploy.log
    - cat $DEPLOYPATH/.env >> $DEPLOYPATH/deploy.log

    - /bin/echo "✅ Deploy finalizado com sucesso"
