deployment:
  tasks:
    - /bin/echo "🚀 Iniciando deploy para ambiente de desenvolvimento"

    - export DEPLOYPATH=/home/mapfrecorretor/public_html/dev
    - export VERSAO=$(date +%Y%m%d%H%M%S)

    # 1. Copia os arquivos primeiro
    - /bin/rsync -a --exclude='.git*' --exclude='vendor/' --exclude='.cpanel.yml' . $DEPLOYPATH

    # 2. Atualiza o .env DENTRO do destino, após copiar
    - /bin/sed -i "s/^CSS_VERSION=.*/CSS_VERSION=$VERSAO/" $DEPLOYPATH/.env
    - /bin/sed -i "s/^JS_VERSION=.*/JS_VERSION=$VERSAO/" $DEPLOYPATH/.env

    # 3. Grava log
    - /bin/echo "Versão: $VERSAO" > $DEPLOYPATH/deploy.log
    - /bin/cat $DEPLOYPATH/.env >> $DEPLOYPATH/deploy.log

    - /bin/echo "✅ Deploy finalizado com sucesso!" 
    - /bin/echo "📅 Data: $(date +'%Y-%m-%d %H:%M:%S')" >> $DEPLOYPATH/deploy.log
